package mediaequipmentrental;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class EquipmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentForm.class.getName());

    
    public EquipmentForm() {
        initComponents();
        loadEquipmentData();
    }
    
    private void loadEquipmentData() {
    String sql = "SELECT equipment_id, name, type, rental_rate FROM equipment";

    try (Connection conn = DBConnection.connect();
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tblEquipment.getModel();

        model.setRowCount(0);

        while (rs.next()) {
            String equipmentID = rs.getString("equipment_id");
            String name = rs.getString("name");
            String type = rs.getString("type");
            double rentalRate = rs.getDouble("rental_rate");

            model.addRow(new Object[]{
                equipmentID,
                name,
                type,
                rentalRate
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Error loading equipment records: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEquipmentID = new javax.swing.JLabel();
        txtEquipmentID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRentalRate = new javax.swing.JLabel();
        txtRentalRate = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        chkAvailable = new javax.swing.JCheckBox();
        btnAddEquipment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCalculateCost = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRentalDays = new javax.swing.JTextField();
        cmbEquipmentType = new javax.swing.JComboBox<>();
        lblEquipmentType = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipment = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnUpdateEquipment = new javax.swing.JButton();
        btnDeleteEquipment = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel1.setText("Media Equipment Rental Management System");

        lblEquipmentID.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        lblEquipmentID.setText("Equipment ID      :");

        lblName.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        lblName.setText("Equipment Name :");

        lblRentalRate.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        lblRentalRate.setText("Rental Rate :");

        lblAvailability.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        lblAvailability.setText("Availability :");

        chkAvailable.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        chkAvailable.setText("Available");
        chkAvailable.addActionListener(this::chkAvailableActionPerformed);

        btnAddEquipment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddEquipment.setText("Add ");
        btnAddEquipment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddEquipment.addActionListener(this::btnAddEquipmentActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnCalculateCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculateCost.setText("Calculate ");
        btnCalculateCost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculateCost.addActionListener(this::btnCalculateCostActionPerformed);

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        jLabel2.setText("Rental Days :");

        cmbEquipmentType.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        cmbEquipmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Equipment Type", "Camera", "Audio Equipment" }));

        lblEquipmentType.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        lblEquipmentType.setText("Equipment Type :");

        tblEquipment.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        tblEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Name", "Type", "Rental Rate", "Availability"
            }
        ));
        jScrollPane2.setViewportView(tblEquipment);

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        jLabel3.setText("Equipment Records");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        jLabel4.setText("Search Equipment ID :");

        btnSearch.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnUpdateEquipment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateEquipment.setText("Update ");
        btnUpdateEquipment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateEquipment.addActionListener(this::btnUpdateEquipmentActionPerformed);

        btnDeleteEquipment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteEquipment.setText("Delete ");
        btnDeleteEquipment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteEquipment.addActionListener(this::btnDeleteEquipmentActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblEquipmentID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAvailability)
                                .addComponent(lblEquipmentType))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(chkAvailable))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbEquipmentType, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(149, 149, 149))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEquipmentID, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRentalRate)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRentalRate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRentalDays, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addComponent(btnAddEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipmentID)
                    .addComponent(txtEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRentalRate)
                    .addComponent(txtRentalRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtRentalDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipmentType)
                    .addComponent(cmbEquipmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(chkAvailable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEquipment)
                    .addComponent(btnClear)
                    .addComponent(btnUpdateEquipment)
                    .addComponent(btnCalculateCost)
                    .addComponent(btnDeleteEquipment))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEquipmentActionPerformed
        
                                                      
            
            String equipmentID = txtEquipmentID.getText().trim();
            String name = txtName.getText().trim();
            String equipmentType = cmbEquipmentType.getSelectedItem().toString();
            
            if (equipmentID.isEmpty() || name.isEmpty() || txtRentalRate.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please fill in all required fields.");
                return;
            }
            if (equipmentType.equals("Choose Equipment Type")) {
                JOptionPane.showMessageDialog(this,
                        "Please choose an equipment type.");
                return;
            }
            
            try {
                double rentalRate = Double.parseDouble(txtRentalRate.getText().trim());
                
                if (rentalRate < 0) {
                    JOptionPane.showMessageDialog(this,
                            "Rental rate cannot be negative.");
                    return;
                }
                
                boolean availability = chkAvailable.isSelected();
                Equipment equipment;
                
                if (equipmentType.equals("Camera")) {
                    equipment = new Camera(
                    equipmentID,
                    name,
                    rentalRate,
                    availability
                    );
                
                } else {
                    equipment = new AudioEquipment(
                    equipmentID,
                    name,
                    rentalRate,
                    availability
                    );
                }
                
                String sql = "INSERT INTO equipment "
                + "(equipment_id, name, type, rental_rate, availability) "
                + "VALUES (?, ?, ?, ?, ?)";
                
                try (Connection conn = DBConnection.connect();
                        PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    
                    pstmt.setString(1, equipment.getEquipmentID());
                    pstmt.setString(2, equipment.getName());
                    pstmt.setString(3, equipmentType);
                    pstmt.setDouble(4, equipment.getRentalRate());
                    pstmt.setInt(5, equipment.isAvailable() ? 1 : 0);
                    pstmt.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this,
                            "Equipment added successfully!");
                
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this,
                            "Database error: " + e.getMessage());
                }
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid rental rate.");
            }
        
    }//GEN-LAST:event_btnAddEquipmentActionPerformed

    private void btnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCostActionPerformed
        
        String rentalRateText = txtRentalRate.getText().trim();
        String rentalDaysText = txtRentalDays.getText().trim();
        String equipmentType = cmbEquipmentType.getSelectedItem().toString();
        
        if (rentalRateText.isEmpty() || rentalDaysText.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter the rental rate and rental days.");
            return;
        }
        
        if (equipmentType.equals("Choose Equipment Type")) {
            JOptionPane.showMessageDialog(this,
                    "Please choose an equipment type.");
            return;
        }
        
        try {
            double rentalRate = Double.parseDouble(rentalRateText);
            int rentalDays = Integer.parseInt(rentalDaysText);
            
            if (rentalRate < 0) {
                JOptionPane.showMessageDialog(this,
                        "Rental rate cannot be negative.");
                return;
            }
            
            if (rentalDays <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Rental days must be greater than 0.");
                return;
            }
            
            Equipment equipment;
            if (equipmentType.equals("Camera")) {
                equipment = new Camera(
                txtEquipmentID.getText().trim(),
                txtName.getText().trim(),
                rentalRate,
                chkAvailable.isSelected()
                );
            
            } else {
                equipment = new AudioEquipment(
                txtEquipmentID.getText().trim(),
                txtName.getText().trim(),
                rentalRate,
                chkAvailable.isSelected()
                );
            }
            double totalCost = equipment.calculateRentalCost(rentalDays);
            JOptionPane.showMessageDialog(this,
                    "Total Rental Cost: RM" + String.format("%.2f", totalCost));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter valid numbers for rental rate and rental days.");
        }
    }//GEN-LAST:event_btnCalculateCostActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtEquipmentID.setText("");
        txtName.setText("");
        txtRentalRate.setText("");
        txtRentalDays.setText("");
        cmbEquipmentType.setSelectedIndex(0);
        chkAvailable.setSelected(false);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String searchID = txtSearch.getText().trim();
        
        if (searchID.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter an Equipment ID to search.");
            return;
        }
        
        String sql = "SELECT equipment_id, name, type, rental_rate, availability "
                + "FROM equipment WHERE equipment_id = ?";
        
        try (Connection conn = DBConnection.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, searchID);
            
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    
                    txtEquipmentID.setText(rs.getString("equipment_id"));
                    txtName.setText(rs.getString("name"));
                    cmbEquipmentType.setSelectedItem(rs.getString("type"));
                    txtRentalRate.setText(String.valueOf(rs.getDouble("rental_rate")));
                    chkAvailable.setSelected(rs.getInt("availability") == 1);
                    JOptionPane.showMessageDialog(this,
                            "Equipment found!");
                
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Equipment not found.");
                }
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEquipmentActionPerformed
        
        String equipmentID = txtEquipmentID.getText().trim();
        String name = txtName.getText().trim();
        String equipmentType = cmbEquipmentType.getSelectedItem().toString();
        String rentalRateText = txtRentalRate.getText().trim();
        
        if (equipmentID.isEmpty() || name.isEmpty() || rentalRateText.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all required fields.");
            return;
        }
        
        if (equipmentType.equals("Choose Equipment Type")) {
            JOptionPane.showMessageDialog(this,
                    "Please choose an equipment type.");
            return;
        }
        
        try {
            double rentalRate = Double.parseDouble(rentalRateText);
            if (rentalRate < 0) {
                JOptionPane.showMessageDialog(this,
                        "Rental rate cannot be negative.");
                return;
            }
            boolean availability = chkAvailable.isSelected();
            
            String sql = "UPDATE equipment SET name = ?, type = ?, "
                    + "rental_rate = ?, availability = ? "
                    + "WHERE equipment_id = ?";
            
            try (Connection conn = DBConnection.connect();
                    PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, name);
                pstmt.setString(2, equipmentType);
                pstmt.setDouble(3, rentalRate);
                pstmt.setInt(4, availability ? 1 : 0);
                pstmt.setString(5, equipmentID);
                
                int rowsUpdated = pstmt.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Equipment updated successfully!");
                    loadEquipmentData();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Equipment ID not found.");
                }
            }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid rental rate.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateEquipmentActionPerformed

    private void btnDeleteEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEquipmentActionPerformed
        
        String equipmentID = txtEquipmentID.getText().trim();
        
        if (equipmentID.isEmpty()) {
            JOptionPane.showMessageDialog(this,
            "Please enter an Equipment ID.");
            return;
        }
        
        String checkSQL = "SELECT equipment_id FROM equipment WHERE equipment_id = ?";
        
        try (Connection conn = DBConnection.connect();
                PreparedStatement checkStmt = conn.prepareStatement(checkSQL)) {
            
            checkStmt.setString(1, equipmentID);
            
            try (ResultSet rs = checkStmt.executeQuery()) {
                
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this,
                            "Equipment ID not found.");
                    return;
                }
            }
            
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete equipment " + equipmentID + "?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION
            );
            
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            
            String deleteSQL = "DELETE FROM equipment WHERE equipment_id = ?";
            
            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteSQL)) {
                deleteStmt.setString(1, equipmentID);
                int rowsDeleted = deleteStmt.executeUpdate();
                
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Equipment deleted successfully!");
                    loadEquipmentData();
                
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Equipment ID not found.");
                }
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteEquipmentActionPerformed

    private void chkAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EquipmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEquipment;
    private javax.swing.JButton btnCalculateCost;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteEquipment;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateEquipment;
    private javax.swing.JCheckBox chkAvailable;
    private javax.swing.JComboBox<String> cmbEquipmentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblEquipmentID;
    private javax.swing.JLabel lblEquipmentType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRentalRate;
    private javax.swing.JTable tblEquipment;
    private javax.swing.JTextField txtEquipmentID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRentalDays;
    private javax.swing.JTextField txtRentalRate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
