package mediaequipmentrental;

import javax.swing.JOptionPane;

public class EquipmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EquipmentForm.class.getName());

    /**
     * Creates new form EquipmentForm
     */
    public EquipmentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEquipmentID = new javax.swing.JLabel();
        txtEquipmentID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRentalRate = new javax.swing.JLabel();
        txtRentalRate = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        chkAvailable = new javax.swing.JCheckBox();
        btnAddEquipment = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCalculateCost = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRentalDays = new javax.swing.JTextField();
        cmbEquipmentType = new javax.swing.JComboBox<>();
        lblEquipmentType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setText("Media Equipment Rental Management System");

        lblEquipmentID.setText("Equipment ID:");

        lblName.setText("Equipment Name:");

        lblRentalRate.setText("Rental Rate:");

        lblAvailability.setText("Availability:");

        chkAvailable.setText("Available");

        btnAddEquipment.setText("Add Equipment");
        btnAddEquipment.addActionListener(this::btnAddEquipmentActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnCalculateCost.setText("Calculate Cost");
        btnCalculateCost.addActionListener(this::btnCalculateCostActionPerformed);

        jLabel2.setText("Rental Days:");

        cmbEquipmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Equipment Type", "Camera", "Audio Equipment" }));

        lblEquipmentType.setText("Equipment Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEquipmentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddEquipment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculateCost))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvailability)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRentalDays, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRentalRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRentalRate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblEquipmentType)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEquipmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEquipmentID)
                    .addComponent(txtEquipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEquipmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipmentType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRentalRate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRentalRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRentalDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(chkAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEquipment)
                    .addComponent(btnClear)
                    .addComponent(btnCalculateCost))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEquipmentActionPerformed
        
        String equipmentID = txtEquipmentID.getText();
        String name = txtName.getText();
        double rentalRate = Double.parseDouble(txtRentalRate.getText());
        boolean availability = chkAvailable.isSelected();
        
        String equipmentType = cmbEquipmentType.getSelectedItem().toString();
        if (equipmentType.equals("Camera")) {
            Camera camera = new Camera(equipmentID, name, rentalRate, availability);
        } else if (equipmentType.equals("Audio Equipment")) {
            AudioEquipment audio = new AudioEquipment(equipmentID, name, rentalRate, availability);
        }
        
        JOptionPane.showMessageDialog(this, "Equipment added successfully!");
    }//GEN-LAST:event_btnAddEquipmentActionPerformed

    private void btnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCostActionPerformed
        
        double rentalRate = Double.parseDouble(txtRentalRate.getText());
        int rentalDays = Integer.parseInt(txtRentalDays.getText());
        String equipmentType = cmbEquipmentType.getSelectedItem().toString();
        
        Equipment equipment;
        
        if (equipmentType.equals("Camera")) {
            equipment = new Camera(
                    txtEquipmentID.getText(),
                    txtName.getText(),
                    rentalRate,
                    chkAvailable.isSelected()
            );
        
        } else {
            equipment = new AudioEquipment(
                    txtEquipmentID.getText(),
                    txtName.getText(),
                    rentalRate,
                    chkAvailable.isSelected()
            );
        }
        double totalCost = equipment.calculateRentalCost(rentalDays);
        JOptionPane.showMessageDialog(this,
                "Total Rental Cost: RM" + totalCost);
    }//GEN-LAST:event_btnCalculateCostActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtEquipmentID.setText("");
        txtName.setText("");
        txtRentalRate.setText("");
        txtRentalDays.setText("");
        chkAvailable.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EquipmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEquipment;
    private javax.swing.JButton btnCalculateCost;
    private javax.swing.JButton btnClear;
    private javax.swing.JCheckBox chkAvailable;
    private javax.swing.JComboBox<String> cmbEquipmentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblEquipmentID;
    private javax.swing.JLabel lblEquipmentType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRentalRate;
    private javax.swing.JTextField txtEquipmentID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRentalDays;
    private javax.swing.JTextField txtRentalRate;
    // End of variables declaration//GEN-END:variables
}
